package com.cgadoury.onthebench.api.model.standing


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Standing(
    @Json(name = "conferenceAbbrev")
    var conferenceAbbrev: String?,
    @Json(name = "conferenceHomeSequence")
    var conferenceHomeSequence: Int?,
    @Json(name = "conferenceL10Sequence")
    var conferenceL10Sequence: Int?,
    @Json(name = "conferenceName")
    var conferenceName: String?,
    @Json(name = "conferenceRoadSequence")
    var conferenceRoadSequence: Int?,
    @Json(name = "conferenceSequence")
    var conferenceSequence: Int?,
    @Json(name = "date")
    var date: String?,
    @Json(name = "divisionAbbrev")
    var divisionAbbrev: String?,
    @Json(name = "divisionHomeSequence")
    var divisionHomeSequence: Int?,
    @Json(name = "divisionL10Sequence")
    var divisionL10Sequence: Int?,
    @Json(name = "divisionName")
    var divisionName: String?,
    @Json(name = "divisionRoadSequence")
    var divisionRoadSequence: Int?,
    @Json(name = "divisionSequence")
    var divisionSequence: Int?,
    @Json(name = "gameTypeId")
    var gameTypeId: Int?,
    @Json(name = "gamesPlayed")
    var gamesPlayed: Int?,
    @Json(name = "goalAgainst")
    var goalAgainst: Int?,
    @Json(name = "goalDifferential")
    var goalDifferential: Int?,
    @Json(name = "goalDifferentialPctg")
    var goalDifferentialPctg: Double?,
    @Json(name = "goalFor")
    var goalFor: Int?,
    @Json(name = "goalsForPctg")
    var goalsForPctg: Double?,
    @Json(name = "homeGamesPlayed")
    var homeGamesPlayed: Int?,
    @Json(name = "homeGoalDifferential")
    var homeGoalDifferential: Int?,
    @Json(name = "homeGoalsAgainst")
    var homeGoalsAgainst: Int?,
    @Json(name = "homeGoalsFor")
    var homeGoalsFor: Int?,
    @Json(name = "homeLosses")
    var homeLosses: Int?,
    @Json(name = "homeOtLosses")
    var homeOtLosses: Int?,
    @Json(name = "homePoints")
    var homePoints: Int?,
    @Json(name = "homeRegulationPlusOtWins")
    var homeRegulationPlusOtWins: Int?,
    @Json(name = "homeRegulationWins")
    var homeRegulationWins: Int?,
    @Json(name = "homeTies")
    var homeTies: Int?,
    @Json(name = "homeWins")
    var homeWins: Int?,
    @Json(name = "l10GamesPlayed")
    var l10GamesPlayed: Int?,
    @Json(name = "l10GoalDifferential")
    var l10GoalDifferential: Int?,
    @Json(name = "l10GoalsAgainst")
    var l10GoalsAgainst: Int?,
    @Json(name = "l10GoalsFor")
    var l10GoalsFor: Int?,
    @Json(name = "l10Losses")
    var l10Losses: Int?,
    @Json(name = "l10OtLosses")
    var l10OtLosses: Int?,
    @Json(name = "l10Points")
    var l10Points: Int?,
    @Json(name = "l10RegulationPlusOtWins")
    var l10RegulationPlusOtWins: Int?,
    @Json(name = "l10RegulationWins")
    var l10RegulationWins: Int?,
    @Json(name = "l10Ties")
    var l10Ties: Int?,
    @Json(name = "l10Wins")
    var l10Wins: Int?,
    @Json(name = "leagueHomeSequence")
    var leagueHomeSequence: Int?,
    @Json(name = "leagueL10Sequence")
    var leagueL10Sequence: Int?,
    @Json(name = "leagueRoadSequence")
    var leagueRoadSequence: Int?,
    @Json(name = "leagueSequence")
    var leagueSequence: Int?,
    @Json(name = "losses")
    var losses: Int?,
    @Json(name = "otLosses")
    var otLosses: Int?,
    @Json(name = "placeName")
    var placeName: PlaceName?,
    @Json(name = "pointPctg")
    var pointPctg: Double?,
    @Json(name = "points")
    var points: Int?,
    @Json(name = "regulationPlusOtWinPctg")
    var regulationPlusOtWinPctg: Double?,
    @Json(name = "regulationPlusOtWins")
    var regulationPlusOtWins: Int?,
    @Json(name = "regulationWinPctg")
    var regulationWinPctg: Double?,
    @Json(name = "regulationWins")
    var regulationWins: Int?,
    @Json(name = "roadGamesPlayed")
    var roadGamesPlayed: Int?,
    @Json(name = "roadGoalDifferential")
    var roadGoalDifferential: Int?,
    @Json(name = "roadGoalsAgainst")
    var roadGoalsAgainst: Int?,
    @Json(name = "roadGoalsFor")
    var roadGoalsFor: Int?,
    @Json(name = "roadLosses")
    var roadLosses: Int?,
    @Json(name = "roadOtLosses")
    var roadOtLosses: Int?,
    @Json(name = "roadPoints")
    var roadPoints: Int?,
    @Json(name = "roadRegulationPlusOtWins")
    var roadRegulationPlusOtWins: Int?,
    @Json(name = "roadRegulationWins")
    var roadRegulationWins: Int?,
    @Json(name = "roadTies")
    var roadTies: Int?,
    @Json(name = "roadWins")
    var roadWins: Int?,
    @Json(name = "seasonId")
    var seasonId: Int?,
    @Json(name = "shootoutLosses")
    var shootoutLosses: Int?,
    @Json(name = "shootoutWins")
    var shootoutWins: Int?,
    @Json(name = "streakCode")
    var streakCode: String?,
    @Json(name = "streakCount")
    var streakCount: Int?,
    @Json(name = "teamAbbrev")
    var teamAbbrev: TeamAbbrev?,
    @Json(name = "teamCommonName")
    var teamCommonName: TeamCommonName?,
    @Json(name = "teamLogo")
    var teamLogo: String?,
    @Json(name = "teamName")
    var teamName: TeamName?,
    @Json(name = "ties")
    var ties: Int?,
    @Json(name = "waiversSequence")
    var waiversSequence: Int?,
    @Json(name = "wildcardSequence")
    var wildcardSequence: Int?,
    @Json(name = "winPctg")
    var winPctg: Double?,
    @Json(name = "wins")
    var wins: Int?
)